import { StyleSheet } from 'react-native';
import { BRAND } from '@/utils/colors';

export const bookingStyles = StyleSheet.create({
  container: { flex: 1 },
  map: { flex: 1 },
  searchExpandedBackground: { ...StyleSheet.absoluteFillObject },
  header: {
    position: 'absolute',
    left: 20,
    right: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 10,
  },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  pillBadge: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  pillText: { color: '#000', fontWeight: '700', fontSize: 16 },
  bottomSheet: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 10,
  },
  handleIndicator: {
    width: 40,
    height: 4,
    backgroundColor: '#E0E0E0',
    borderRadius: 2,
    alignSelf: 'center',
    marginTop: 12,
    marginBottom: 8,
  },
  dragHandleZone: { paddingTop: 2, paddingBottom: 2 },
  recentRoutesWrap: { marginBottom: 14 },
  recentRoutesTitle: { fontSize: 21, fontWeight: '900', marginBottom: 10, letterSpacing: 0 },
  recentRoutesList: { gap: 8, paddingRight: 8 },
  recentRouteCard: {
    width: 132,
    minHeight: 128,
    borderWidth: 1,
    borderRadius: 8,
    padding: 10,
    justifyContent: 'space-between',
  },
  recentRouteIconBadge: {
    width: 44,
    height: 36,
    borderRadius: 8,
    backgroundColor: 'rgba(255, 149, 0, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  recentRouteMain: { fontSize: 13, lineHeight: 16, fontWeight: '900', minHeight: 32 },
  recentRouteSub: { fontSize: 10, lineHeight: 13, fontWeight: '700', marginTop: 3 },
  recentRouteMetaRow: { marginTop: 8, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 6 },
  recentRouteFare: { fontSize: 12, fontWeight: '900' },
  recentRouteTime: { flex: 1, textAlign: 'right', fontSize: 10, fontWeight: '800' },
  stepSheet: {
    position: 'absolute',
    left: 0,
    right: 0,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 12,
  },
  sheetGrabberWrap: {
    alignItems: 'center',
    paddingTop: 4,
    paddingBottom: 10,
  },
  sheetGrabber: {
    width: 42,
    height: 5,
    borderRadius: 999,
    backgroundColor: 'rgba(128,128,128,0.28)',
  },
  guideBoxCompact: { marginTop: 10, paddingVertical: 9 },
  stepContent: { paddingHorizontal: 20, paddingBottom: 14 },
  stepHeaderRight: {
    minWidth: 58,
    alignItems: 'flex-end',
  },
  stepBackGhost: {
    width: 38,
    height: 38,
  },
  stepPill: {
    minWidth: 58,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: BRAND.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepPillText: {
    color: '#000',
    fontSize: 13,
    fontWeight: '800',
  },
  locationFieldCard: {
    gap: 8,
  },
  locationFieldLabel: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  locationFieldInputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: 18,
    paddingHorizontal: 14,
    minHeight: 56,
    gap: 10,
  },
  locationFieldInput: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
  },
  locationFieldClear: {
    padding: 2,
  },
  quickLocationSection: {
    gap: 10,
  },
  quickLocationHeader: {
    gap: 2,
  },
  quickLocationTitle: {
    fontSize: 13,
    fontWeight: '800',
  },
  quickLocationSubtitle: {
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 16,
  },
  quickLocationCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  quickLocationLabel: {
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 2,
  },
  quickLocationValue: {
    fontSize: 12,
    fontWeight: '500',
  },
  recentChipsRow: {
    gap: 10,
    paddingRight: 8,
  },
  recentChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 10,
    maxWidth: 220,
  },
  recentChipText: {
    fontSize: 12,
    fontWeight: '600',
    maxWidth: 170,
  },
  locationActionsRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 14,
  },
  locationActionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 1,
    borderRadius: 16,
    paddingVertical: 12,
  },
  locationActionText: {
    fontSize: 13,
    fontWeight: '700',
  },
  stepHeader: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 10 },
  stepBackButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 18,
  },
  stepTitleWrap: { flex: 1 },
  stepEyebrow: { fontSize: 11, fontWeight: '900', textTransform: 'uppercase', marginBottom: 2 },
  stepTitle: { fontSize: 22, fontWeight: '900', letterSpacing: 0 },
  previousChoiceCard: {
    minHeight: 48,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 9,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  previousChoiceLabel: { fontSize: 10, fontWeight: '900', textTransform: 'uppercase', marginBottom: 2 },
  previousChoiceValue: { fontSize: 13, fontWeight: '800' },
  previousChoiceEdit: { fontSize: 12, fontWeight: '900' },
  choiceSummary: { flexDirection: 'row', gap: 8, marginBottom: 14 },
  choiceChip: {
    flex: 1,
    minHeight: 40,
    borderRadius: 14,
    backgroundColor: 'rgba(255, 149, 0, 0.08)',
    paddingHorizontal: 10,
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  choiceChipActive: {
    backgroundColor: 'rgba(255, 149, 0, 0.18)',
    borderWidth: 1,
    borderColor: BRAND.primary,
  },
  choiceChipText: { flex: 1, fontSize: 11, fontWeight: '800' },
  stepSearchCard: {
    minHeight: 54,
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  stepSearchInput: { flex: 1, minHeight: 44, fontSize: 18, fontWeight: '800', paddingVertical: 0 },
  stepIconButton: { width: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  quickPickRow: { flexDirection: 'row', gap: 8, marginTop: 8, marginBottom: 8 },
  quickPickButton: {
    flex: 1,
    minHeight: 40,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  quickPickText: { flex: 1, fontSize: 12, fontWeight: '800' },
  quickIconButton: {
    width: 44,
    height: 40,
    borderRadius: 14,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  whenPanel: {
    minHeight: 84,
    borderRadius: 18,
    borderWidth: 1,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  whenButton: { height: 42, borderRadius: 14, paddingHorizontal: 18, alignItems: 'center', justifyContent: 'center' },
  whenButtonText: { color: '#000', fontSize: 14, fontWeight: '900' },
  whenSelectedLabel: { fontSize: 12, fontWeight: '800', marginBottom: 4 },
  whenSelectedValue: { fontSize: 17, fontWeight: '900' },
  simpleFareCard: { marginTop: 2, padding: 16, borderRadius: 18, borderWidth: 1 },
  simpleFareLabel: { fontSize: 12, fontWeight: '800' },
  simpleFareValue: { fontSize: 30, fontWeight: '900', marginTop: 2 },
  simpleFareMeta: { flexDirection: 'row', gap: 12, marginTop: 8, marginBottom: 4 },
  simpleFareMetaText: { fontSize: 12, fontWeight: '800' },
  compactFareBreakdown: { marginTop: 12, paddingTop: 10, borderTopWidth: 1, gap: 4 },
  reviewButton: {
    marginTop: 14,
    height: 56,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: BRAND.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.24,
    shadowRadius: 8,
    elevation: 6,
  },
  reviewButtonText: { color: '#000', fontSize: 16, fontWeight: '900' },
  scrollContent: { padding: 20 },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 8,
  },
  inputIcon: { marginTop: 4 },
  label: { fontSize: 12, fontWeight: '600', marginBottom: 4 },
  input: {
    flex: 1,
    fontSize: 16,
    fontWeight: '500',
    padding: 0,
    paddingRight: 30,
    height: 24,
  },
  searchInputWrap: { flexDirection: 'row', alignItems: 'center', flex: 1, position: 'relative' },
  clearButton: { position: 'absolute', right: 0, top: -2, padding: 4 },
  selectedRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', paddingTop: 2 },
  selectedText: { fontSize: 15, fontWeight: '600', flex: 1, marginRight: 8, lineHeight: 20 },
  mapIconBtn: { padding: 8 },
  divider: { height: 1, marginVertical: 12, marginLeft: 32 },
  resultsList: {
    marginTop: 8,
    borderRadius: 12,
    padding: 10,
    maxHeight: 210,
  },
  resultsScrollView: {
    maxHeight: 154,
  },
  resultsHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, marginBottom: 8 },
  resultsTitle: { flex: 1, fontSize: 10, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.5 },
  resultsCloseButton: { width: 28, height: 28, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  resultsHint: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 7,
    marginBottom: 8,
  },
  resultsHintText: { flex: 1, fontSize: 11, fontWeight: '600', lineHeight: 15 },
  resultItem: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, paddingVertical: 9, paddingHorizontal: 4 },
  resultText: { fontSize: 13, flex: 1, lineHeight: 18 },
  emptyResults: { alignItems: 'center', paddingVertical: 22 },
  emptyText: { fontSize: 13, marginTop: 8 },
  fareCard: {
    marginTop: 20,
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
  },
  fareRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  fareLabel: { fontSize: 12, fontWeight: '500' },
  fareValue: { fontSize: 24, fontWeight: '700', marginTop: 2 },
  fareValueSmall: { fontSize: 16, fontWeight: '600', marginTop: 2 },
  fareMetaRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  fareMetaText: { fontSize: 12, fontWeight: '500' },
  fareBreakdown: { marginTop: 12, paddingTop: 12, borderTopWidth: 1, gap: 8 },
  fareTotalLabel: { fontSize: 13, fontWeight: '800' },
  fareTotalValue: { fontSize: 15, fontWeight: '900' },
  bookBtn: {
    marginTop: 24,
    height: 56,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: BRAND.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  bookBtnText: { color: '#000', fontSize: 16, fontWeight: '700' },
  successOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  successCard: {
    width: '100%',
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
  },
  successTitle: {
    marginTop: 10,
    fontSize: 20,
    fontWeight: '700',
    textAlign: 'center',
  },
  successMessage: {
    marginTop: 8,
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 20,
  },
  successBtn: {
    marginTop: 18,
    backgroundColor: BRAND.primary,
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 16,
    width: '100%',
    alignItems: 'center',
  },
  successBtnText: {
    color: '#000',
    fontSize: 15,
    fontWeight: '700',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 22,
  },
  confirmModal: {
    width: '100%',
    maxWidth: 430,
    borderRadius: 24,
    borderWidth: 1,
    padding: 20,
  },
  confirmIcon: {
    width: 58,
    height: 58,
    borderRadius: 29,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginBottom: 12,
  },
  confirmTitle: { fontSize: 22, fontWeight: '900', textAlign: 'center' },
  confirmCopy: { marginTop: 8, fontSize: 13, lineHeight: 19, textAlign: 'center' },
  confirmRoute: { marginTop: 16, borderWidth: 1, borderRadius: 16, padding: 14, gap: 8 },
  confirmAddress: { fontSize: 13, fontWeight: '700', lineHeight: 18 },
  confirmRows: { marginTop: 16, gap: 10 },
  confirmRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12 },
  confirmLabel: { fontSize: 13, flex: 1 },
  confirmValue: { fontSize: 14, fontWeight: '800' },
  confirmTotalRow: { marginTop: 2, paddingTop: 12, borderTopWidth: 1 },
  confirmTotalLabel: { fontSize: 15, fontWeight: '900', flex: 1 },
  confirmTotalValue: { fontSize: 20, fontWeight: '900' },
  confirmActions: { flexDirection: 'row', gap: 10, marginTop: 20 },
  confirmButton: { flex: 1, minHeight: 48, borderRadius: 14, borderWidth: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 10 },
  confirmButtonText: { fontSize: 14, fontWeight: '900', textAlign: 'center' },
  voiceModal: {
    width: '100%',
    borderRadius: 22,
    borderWidth: 1,
    padding: 20,
    alignItems: 'center',
  },
  voiceIcon: {
    width: 58,
    height: 58,
    borderRadius: 29,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  voiceTitle: {
    fontSize: 20,
    fontWeight: '900',
    textAlign: 'center',
  },
  voiceCopy: {
    marginTop: 8,
    fontSize: 13,
    lineHeight: 19,
    textAlign: 'center',
  },
  voiceInput: {
    width: '100%',
    marginTop: 16,
    minHeight: 52,
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 14,
    fontSize: 15,
    fontWeight: '600',
  },
  voiceRecordButton: {
    minHeight: 48,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 18,
    marginTop: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  voiceRecordText: {
    fontSize: 14,
    fontWeight: '900',
  },
  voiceErrorText: {
    marginTop: 10,
    color: '#B3261E',
    fontSize: 12,
    lineHeight: 17,
    textAlign: 'center',
    fontWeight: '700',
  },
  voiceActions: {
    width: '100%',
    flexDirection: 'row',
    gap: 10,
    marginTop: 14,
  },
  voiceButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 14,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  voiceButtonText: {
    fontSize: 14,
    fontWeight: '900',
  },
  guideBox: { marginTop: 20, padding: 12, borderRadius: 12, flexDirection: 'row', alignItems: 'center', gap: 10 },
  guideText: { fontSize: 12, flex: 1, lineHeight: 18 },
  greetingSection: { marginBottom: 20 },
  greetingText: { fontSize: 12, fontWeight: '600', textTransform: 'uppercase', letterSpacing: 0.5, marginLeft: 10 },
  promptText: { fontSize: 24, fontWeight: '700', marginTop: 4, marginLeft: 10},
  warningOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  warningCard: {
    width: '100%',
    borderRadius: 18,
    padding: 18,
    alignItems: 'center',
    borderWidth: 1,
  },
  warningTitle: {
    marginTop: 10,
    fontSize: 18,
    fontWeight: '800',
  },
  warningText: {
    marginTop: 8,
    fontSize: 13,
    lineHeight: 19,
    textAlign: 'center',
  },
  warningButton: {
    marginTop: 16,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    width: '100%',
    alignItems: 'center',
  },
  warningButtonText: {
    color: '#000',
    fontWeight: '800',
  },
  locationWaitOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  locationWaitCard: {
    width: '100%',
    maxWidth: 320,
    borderWidth: 1,
    borderRadius: 18,
    padding: 18,
    alignItems: 'center',
  },
  locationWaitTitle: {
    marginTop: 12,
    fontSize: 18,
    fontWeight: '900',
  },
  locationWaitText: {
    marginTop: 6,
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
  },
});

export { mapDarkStyle };


const mapDarkStyle = [
  { "elementType": "geometry", "stylers": [{ "color": "#242f3e" }] },
  { "elementType": "labels.text.fill", "stylers": [{ "color": "#746855" }] },
  { "elementType": "labels.text.stroke", "stylers": [{ "color": "#242f3e" }] },
  { "featureType": "administrative.locality", "elementType": "labels.text.fill", "stylers": [{ "color": "#d59563" }] },
  { "featureType": "poi", "elementType": "labels.text.fill", "stylers": [{ "color": "#d59563" }] },
  { "featureType": "poi.park", "elementType": "geometry", "stylers": [{ "color": "#263c3f" }] },
  { "featureType": "poi.park", "elementType": "labels.text.fill", "stylers": [{ "color": "#6b9a76" }] },
  { "featureType": "road", "elementType": "geometry", "stylers": [{ "color": "#38414e" }] },
  { "featureType": "road", "elementType": "geometry.stroke", "stylers": [{ "color": "#212a37" }] },
  { "featureType": "road", "elementType": "labels.text.fill", "stylers": [{ "color": "#9ca5b3" }] },
  { "featureType": "road.highway", "elementType": "geometry", "stylers": [{ "color": "#746855" }] },
  { "featureType": "road.highway", "elementType": "geometry.stroke", "stylers": [{ "color": "#1f2835" }] },
  { "featureType": "road.highway", "elementType": "labels.text.fill", "stylers": [{ "color": "#f3d19c" }] },
  { "featureType": "transit", "elementType": "geometry", "stylers": [{ "color": "#2f3948" }] },
  { "featureType": "transit.station", "elementType": "labels.text.fill", "stylers": [{ "color": "#d59563" }] },
  { "featureType": "water", "elementType": "geometry", "stylers": [{ "color": "#17263c" }] },
  { "featureType": "water", "elementType": "labels.text.fill", "stylers": [{ "color": "#515c6d" }] },
  { "featureType": "water", "elementType": "labels.text.stroke", "stylers": [{ "color": "#17263c" }] }
];


